apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: helloworld
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: 'runtime/default'
    seccomp.security.alpha.kubernetes.io/defaultProfileName:  'runtime/default'
spec:
  allowedCapabilities:
    - NET_BIND_SERVICE
  privileged: false
  allowPrivilegeEscalation: false
  volumes:
    - projected
  hostNetwork: false
  hostIPC: false
  hostPID: false
  runAsUser:
    rule: RunAsAny #MustRunAsNonRoot
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: MustRunAs
    ranges:
      - min: 65535
        max: 65535
  fsGroup:
    rule: MustRunAs
    ranges:
      - min: 65535
        max: 65535
  readOnlyRootFilesystem: false
  defaultAddCapabilities:
    - NET_BIND_SERVICE
  requiredDropCapabilities:
    - ALL
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: helloworld-psp-role
rules:
  - apiGroups: [policy]
    resources: [podsecuritypolicies]
    verbs: [use]
    resourceNames: [helloworld]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: helloworld-psp-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: helloworld-psp-role
subjects:
  - kind: ServiceAccount
    name: default
